version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./src/db:/app/src/db
    command: [ 'python3', './src/manage.py', 'runserver', '0.0.0.0:8000']

  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./src/cats:/app/src/cats
    command: [ 'celery', '--workdir=./src', '-A', 'cat_downloader', 'worker']

  celery-beats:
    restart: always
    build:
      context: .
    volumes:
      - ./src/db:/app/src/db
    command: [ 'celery', '--workdir=./src', '-A', 'cat_downloader', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler']